name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - blazecodedev
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? (publicly visible)
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: What device does the bug happen on?
      placeholder: Pixel 6 Pro
    validations:
      required: true
  - type: input
    id: version-android
    attributes:
      label: Android version
      description: What Android version are you using?
      placeholder: Android 13
    validations:
      required: true
  - type: input
    id: version-app
    attributes:
      label: App version
      description: What version of the app are you using?
      placeholder: V1.4
    validations:
      required: true
